/**
 * Learning Package API
 * API for managing learning packages and associated facts.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {SwaggerJsonInfo} from './swaggerJsonInfo';

export interface SwaggerJson {
  swagger?: string;
  info?: SwaggerJsonInfo;
}
